### ISSUE TITLE
Minor request - add f-droid link to description

### ISSUE THREAD

**Issue by OffifialMITX** [Crazy-Marvin/Morse#10]
```

<a href="https://f-droid.org/app/rocks.poopjournal.morse">

<img alt="Get it on F-Droid"

height="80"

src="https://gitlab.com/fdroid/artwork/raw/master/badge/get-it-on-en-us.svg" />

</a> 


```

**Comment by CrazyMarvin** [comment]
Thanks for your message, @OffifialMITX.

Sorry, I do not get exactly what you mean. 🤔

This is how the Readme looks like:
![readme](https://user-images.githubusercontent.com/15004217/62271576-3d887780-b439-11e9-9e50-fda515148702.PNG)

There are two badges quite at the top for Google Play and F-Droid already.
What would you like to add exactly?

**Comment by OffifialMITX** [comment]
Hm, strange, It wasn't there before… pobably didn't load properly. Sorry.

**Comment by CrazyMarvin** [comment]
Yes, sometimes those images don't load properly. I noticed that here and on other repos too.
