### ISSUE TITLE
Themed Icon for Android 13+

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Morse#115]
Google introduced a new icon technique starting with Android 13 and higher called [Themed Icons](https://developer.android.com/about/versions/13/features#themed-app-icons). 

![ic_monochrome](https://user-images.githubusercontent.com/15004217/190926939-ea672be6-bebb-4f52-8222-08e6c59b0ed2.svg)

**Comment by HatakeKakashri** [comment]
Hi @CrazyMarvin,

I would like to work on this task. Will add more details here on how I plan to proceed.

**Comment by pantheism2709** [comment]
I want to do this task ,please assign it to me @CrazyMarvin

**Comment by HatakeKakashri** [comment]
@CrazyMarvin Please review the changes https://github.com/Crazy-Marvin/Morse/pull/117

**Comment by CrazyMarvin** [comment]
Thank you very much for your help, @snaik20! 😘

@sachin2709, this is a similar issue: https://github.com/Crazy-Marvin/ToDont/issues/139. Would you like to work on this?
