### ISSUE TITLE
Google Play Version 1.9 can't be opened

### ISSUE THREAD

**Issue by occultID** [Crazy-Marvin/Morse#141]
java.lang.RuntimeException: Unable to start activity ComponentInfo{rocks.poopjournal.morse/rocks.poopjournal.morse.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by CrazyMarvin** [comment]
Thanks for the report. I verified that and will upload a new release to Google Play.

**Comment by Enrico204** [comment]
Actually, the same issue is present in the F-Droid repository. The previous version (1.8) is working properly

**Comment by Anke** [comment]
Thanks for this app! 

I'm having the same problem: version 1.9 is not opening, but 1.8 seems to be working fine. 

However, since I installed and uninstalled version 1.9, my favourite news app (tagesschau.de) is stubbornly crashing on start up. I'm just a normal user, so please excuse the question: is it possible that there's connection, that Morse maybe killed some important OS function/service?
(I'm using a Murena One with de-googled Android 11, respectively /e/OS 1.8.1)

**Comment by CrazyMarvin** [comment]
> Thanks for this app! 
> 
> I'm having the same problem: version 1.9 is not opening, but 1.8 seems to be working fine. 
> 
> However, since I installed and uninstalled version 1.9, my favourite news app (tagesschau.de) is stubbornly crashing on start up. I'm just a normal user, so please excuse the question: is it possible that there's connection, that Morse maybe killed some important OS function/service?
> (I'm using a Murena One with de-googled Android 11, respectively /e/OS 1.8.1)

Thanks for your kind words.

Don't worry, Anke. I messed something up when optimizing the app for Android 13+. Other apps and the OS are not impacted.

**Comment by CrazyMarvin** [comment]
I released [`v2.0` ](https://github.com/Crazy-Marvin/Morse/releases/tag/v2.0) today which should fix the startup issues. Sorry for the inconvenience.

**Comment by occultID** [comment]
> I released [`v2.0` ](https://github.com/Crazy-Marvin/Morse/releases/tag/v2.0) today which should fix the startup issues. Sorry for the inconvenience.

thank you very much，now i can open it successfully

**Comment by CrazyMarvin** [comment]
> > I released [`v2.0` ](https://github.com/Crazy-Marvin/Morse/releases/tag/v2.0) today which should fix the startup issues. Sorry for the inconvenience.
> 
> thank you very much，now i can open it successfully

I'm glad to hear that. Thanks for the feedback. 👍
