### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by paulle** [Crazy-Marvin/Morse#19]
The font size is very tiny, this makes it hard to read text or Morse code.
Please make the font size bigger or include an option for choosing the font size.

**Comment by CrazyMarvin** [comment]
Thanks for your suggestion, @paulle. 
Did you try to change the size using the system's settings? Does that work?

**Comment by paulle** [comment]
@CrazyMarvin, in system settings I use a big font size, but it seems your program is not influenced by this. The text/morse code is very small.

**Comment by CrazyMarvin** [comment]
That is strange. 🤔

@FahadSaleem, can you please have a look? And do you have some ideas for improving the situation?

I tried it on my device and the font size changes; but not very much. 

Here is the _standard/normal_ size:
![Morse_font_normal](https://user-images.githubusercontent.com/15004217/67970421-3d03a680-fc0b-11e9-8a07-23ba82f0be45.jpg)

Here is the _very big_ size:
![Morse_font_verybig](https://user-images.githubusercontent.com/15004217/67970430-41c85a80-fc0b-11e9-87f4-d0378772fd7b.jpg)

**Comment by CrazyMarvin** [comment]
@paulle, we increased the Morse and text size in the [latest release](https://github.com/Crazy-Marvin/Morse/releases/tag/1.3). Can you please check if that works for you?

**Comment by heinrichreimer** [comment]
Closed by #20

**Comment by paulle** [comment]
I will inform when the version is on f-droid.

Am 5. November 2019 14:31:11 MEZ schrieb CrazyMarvin <notifications@github.com>:
>@paulle, we increased the Morse and text size in the [latest
>release](https://github.com/Crazy-Marvin/Morse/releases/tag/1.3). Can
>you please check if that works for you?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Crazy-Marvin/Morse/issues/19#issuecomment-549821207

-- 
K-9 Mail

**Comment by paulle** [comment]
I've now v1.2 installed. Font size remains the same. Will see what happens with v1.3 when it is on f-droid in some days.
