### ISSUE TITLE
No support for digits?

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Crazy-Marvin/Morse#32]
I try to convert digits to Morse code in this app, but the app doesn’t responce them. I used your Morse app v1.4 from F-Droid.

Here is the Morse code for mumbers:
```
0 -----
1 ·---- 
2 ··---
3 ···--
4 ····-
5 ·····
6 -····
7 --···
8 ---··
9 ----·
```
See: https://en.wikipedia.org/wiki/Morse_code#Letters,_numbers,_punctuation,_prosigns_for_Morse_code_and_non-English_variants

**Comment by CrazyMarvin** [comment]
Thanks for opening an issue. Digits will be supported in the next release v1.5. 👌

**Comment by CrazyMarvin** [comment]
The new version v1.5 should be available on F-Droid and Google Play soon. Alternatively you can download the .apk from the [releases](https://github.com/Crazy-Marvin/Morse/releases).
