### ISSUE TITLE
Add screenshot to README.md

### ISSUE THREAD

**Issue by luc65r** [Crazy-Marvin/Morse#41]
Hi, it would be great if you added a screenshot in README.md so people can see what does the app look like.
I honestly find it looks great, it is unfortunate to not show it!

**Comment by CrazyMarvin** [comment]
Hi, thanks for your feedback and support.
Credit for the design goes to @lumiqcreative.
After implementing the Morse key (#38) I will add screenshots to the README.md.

**Comment by CrazyMarvin** [comment]
Hey @luc65r, Morse version 1.6 will be released soon. Are you interested in doing the screenshots yourself then?
