### ISSUE TITLE
Hosted Weblate Integration

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Morse#50]

**Comment by comradekingu** [comment]
How about using Weblate instead? I can contribute without issue then.

**Comment by CrazyMarvin** [comment]
I tried to register for [Hosted Weblate](https://hosted.weblate.org/about/) but they did not accept my project. Crowdin warmly welcomed me so I will stay with them. I appreciate that Weblate has better ToS though.

**Comment by CrazyMarvin** [comment]
Next month I will try to register the project again.

**Comment by comradekingu** [comment]
@CrazyMarvin
You can set it up yourself now on https://hosted.weblate.org/hosting/
There is also https://weblate.bubu1.eu/ :)

**Comment by CrazyMarvin** [comment]
Registration on Hosted Weblate was succesful some time ago. 😃
