### ISSUE TITLE
Play Morse code as a really loud, high pitched whistle

### ISSUE THREAD

**Issue by ElonSatoshi** [Crazy-Marvin/Morse#57]
Try the whistle in [Trail Sense](https://github.com/kylecorry31/Trail-Sense/) to see what I mean

**Comment by CrazyMarvin** [comment]
I will have a look.

**Comment by CrazyMarvin** [comment]
I don't plan to implement such a feature.
It really fits inside Trail Sense and I recommend to use that app when you go outside.
