### ISSUE TITLE
Morse 1.6 flashlight button

### ISSUE THREAD

**Issue by akissz** [Crazy-Marvin/Morse#60]
I updated from 1.5 to 1.6 today and the flashlight button just flashes one long flash without doing anything more. But I thought the previous version 1.5 functioned correctly on off on off, etc, etc. I think my android version is 9.1.

**Comment by CrazyMarvin** [comment]
Oh no, I noticed that too. I hope to fix the bug next week. Sorry for the trouble. 😅

**Comment by FahadSaleem** [comment]
@akissz please mention the mobile device you are using as well

**Comment by akissz** [comment]
The device is a Huawei Y5

**Comment by CrazyMarvin** [comment]
The issue is fixed.
