### ISSUE TITLE
Last Sound Is Lost

### ISSUE THREAD

**Issue by EkriirkE** [Crazy-Marvin/Morse#64]
The last sound on a sequence is not played.  E.g. SOS shows . . . _ _ _ . . .  but only plays back . . . _ _ _ . .

In the meantime I add an extra E to the end

**Comment by CrazyMarvin** [comment]
Hey, thanks for noticing. 👍
Which device and Android version do you use?

**Comment by FahadSaleem** [comment]
Thanks for the bug. This is known, a fix is on the way.

**Comment by CrazyMarvin** [comment]
This bug is still active.
Let me know if you would like to work on it.

**Comment by fejd** [comment]
Could I work on this? I tested and it crashes on my device after the last sound is played.

**Comment by CrazyMarvin** [comment]
> Could I work on this? I tested and it crashes on my device after the last sound is played.

That would be awesome! 😎
