### ISSUE TITLE
Morse Code cannot be pasted into the Morse input box

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Morse#76]
It is possible to paste something from the clipboard into the text field but pasting something into the Morse field is not available.

Pasting possible:
![PastingPossible](https://github.com/Crazy-Marvin/Morse/assets/15004217/e195e54b-0451-42ed-ae03-4ba1ae43acb6)

Pasting not active:
![PastingNotPossible](https://github.com/Crazy-Marvin/Morse/assets/15004217/7bd49492-3204-4c0f-824a-455512e52fc9)

**Comment by CrazyMarvin** [comment]
Are you interested to work on this too, @fejd? 😅

**Comment by fejd** [comment]
I could give it a try. 🙂 What are the reproduction steps?

**Comment by CrazyMarvin** [comment]
> I could give it a try. 🙂 What are the reproduction steps?

I put screenshots and a description inside the first comment now. 😅
Do you understand what I mean?

**Comment by fejd** [comment]
Sure, I'll take a look!
