### ISSUE TITLE
Use smartphone's LED flashlight for translation

### ISSUE THREAD

**Issue by Larnicone** [Crazy-Marvin/Morse#8]
First, thanks for this useful and open source application. 🙂

Maybe it would be interesting to add the possibility of translating into Morse thanks to the smartphone's flashlight, in addition to the sound translation, if possible.

**Comment by CrazyMarvin** [comment]
Thanks for your message, @Larnicone.
I will try to implement that feature. But it will take some time. 😅

**Comment by hieutvan** [comment]
@CrazyMarvin
I will be glad if I'm allowed to help you with implement that. What do you think?

**Comment by CrazyMarvin** [comment]
Please try [version 1.2](https://github.com/Crazy-Marvin/Morse/releases/tag/1.2) and tell me if the flashlight feature works for you, @Larnicone.

**Comment by Larnicone** [comment]
Thank you so much. I just tested this new version. It's great, and the flashlight works like a charm. I can' t wait to see it releasing on f-droid. 🙂 👍

**Comment by CrazyMarvin** [comment]
I am very glad to hear that! 😊
