### ISSUE TITLE
Support punctuations

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Crazy-Marvin/Morse#95]
If this app could be able to convert a punctuation to morse code or vice versa, this app can present not only a simple phrase like _SOS_ or _Hello World_ but also a complete sentence.

**Comment by CrazyMarvin** [comment]
This would be a great improvement.  
@FahadSaleem is working on refactoring the code and maybe he can directly implement support for punctuations.

**Comment by CrazyMarvin** [comment]
I suppose the punctuations on https://morsecode.world/international/morse.html would be a good start.

**Comment by CrazyMarvin** [comment]
Are you interested to help with this too, @fejd? 😅

You have done so much so it's fine if you say no.

**Comment by fejd** [comment]
Sure, I could take a look. Is the code refactoring still in progress? I was thinking of breaking things out of the main activity and perhaps convert some of that functionality to Kotlin in the process. :)

If I understand the feature request correctly, there should be a mapping of punctuations from the "Punctuation Mark" table in https://morsecode.world/international/morse.html to dots/dahs. 

I noticed on https://morsecode.world/international/timing.html that the timing is different depending on the type of space between characters and words. I should probably revisit the sound playback and adapt the pause between sounds based on that. Also, maybe it's useful to share the "playback algorithm" between audio, camera flash and "screen flash"?

**Comment by CrazyMarvin** [comment]
The refactoring did not start yet unfortunately. So feel welcome to start with it. 😅

Yes, you understood this correctly. 👍

There is another issue about the timing: https://github.com/Crazy-Marvin/Morse/issues/36. 
This is a bit more complex but it would be awesome if you could tackle it though.

**Comment by Noitarud** [comment]
I only have:
![morse-sec001a4](https://user-images.githubusercontent.com/98794719/234262993-c1ed9723-6069-4300-894e-0ddf782e8e58.gif)

**Comment by CrazyMarvin** [comment]
Do you have time for this or are you busy, @fejd?

**Comment by fejd** [comment]
@CrazyMarvin Sorry, I'll be a bit busy for the next 3-4 months.

**Comment by CrazyMarvin** [comment]
> @CrazyMarvin Sorry, I'll be a bit busy for the next 3-4 months.

Alright, thanks for the info. 👍
